{{- if and .Values.envFromConfigMap.enabled (not .Values.envFromConfigMap.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
