{{- if and .Values.envFromSecret.enabled (not .Values.envFromSecret.existingSecret) (not .Values.externalSecrets.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
