apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.container.protocol }}
      name: http
  selector:
    {{- include "generic-service.selectorLabels" . | nindent 4 }}
